import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// PLACEHOLDER — this file is normally generated by `flutterfire configure`,
/// which fills in your Firebase project's real keys. Until you run it, push
/// notifications are disabled *gracefully*: PushService catches the error
/// thrown below and the app keeps working (in-app notifications and the local
/// daily-verse alarm are unaffected).
///
/// To enable phone push:
///   1. Create a Firebase project and an Android app (package
///      com.christianyouth.superapp).
///   2. `dart pub global activate flutterfire_cli`
///   3. From apps/mobile: `flutterfire configure` — this overwrites this file.
///   4. Add the FCM service-account JSON to the worker (FCM_SERVICE_ACCOUNT).
/// See docs/push-notifications-setup.md for the full walkthrough.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    throw UnsupportedError(
      'Firebase is not configured. Run `flutterfire configure` in apps/mobile '
      'to generate firebase_options.dart. See docs/push-notifications-setup.md.',
    );
  }
}
